name = input("What is your name?")
print("Hello", name)
age = input("How old are you?")
print(name, "you were born in", 2024-int(age))
#another way too format the print is via f-strings (to be taught)
print(f"{name}, you were born in {2024-int(age)}")
